baseURL = "https://sean.mcgrath.nz/"
languageCode = "en-us"
title = "Sean McGrath"
theme = ["hugo-notice", "yinyang"]
newContentEditor = "vim"
metaDataFormat = "toml"
PygmentsCodeFences = true
PygmentsCodefencesGuessSyntax = true
PygmentsStyle = "monokailight"
extraCSSFiles = ["css/override.css"]

enableEmoji = true


[params]
  disqus = "seanmcgrathnz"
  mainSections = ["post"]
  copyrightContent = "© 2019 Sean McGrath"
  extraHead = "<script async src='https://www.googletagmanager.com/gtag/js?id=UA-10214740-7'></script><script>window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-10214740-7');</script>"


[author]
  name = "Sean McGrath"
  homepage = "https://sean.mcgrath.nz"
  email = "sean@mcgrath.nz"
  github = "wipash"
  gitlab = "wipash"
  linkedin = "sean-m-mcgrath"

# [[params.socials]]
#   name = "About"
#   link = "/page/about"
[[params.socials]]
  name = "GitHub"
  link = "https://github.com/wipash"
[[params.socials]]
  name = "GitLab"
  link = "https://gitlab.com/wipash"

[markup.goldmark.renderer]
  unsafe= true
