baseURL = "https://sean.mcgrath.nz/"
languageCode = "en-us"
title = "Sean's Blog"
theme = "beautifulhugo"
newContentEditor = "vim"
metaDataFormat = "toml"
PygmentsCodeFences = true
PygmentsCodefencesGuessSyntax = true
PygmentsStyle = "dracula"
disqusShortname = "seanmcgrathnz"
googleAnalytics = "UA-10214740-7"
summaryLength = 30
enableEmoji = true
copyright = "Copyright &copy; 2019 - Sean McGrath"
canonifyurls = true

[params]
  subtitle = "A blog about technology"
  logo = "img/logo.png"
  dateFormat = "Jan 2, 2006"
  rss = true
  comments = true
  readingTime = false
  socialShare = true

[author]
  name = "Sean McGrath"
  website = "https://sean.mcgrath.nz"
  email = "sean@mcgrath.nz"
  github = "wipash"
  gitlab = "wipash"
  linkedin = "sean-m-mcgrath"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 2
